version: "3"
services:
  web:
    build: . # 需要dockerfile文件
    links:
      - redis
    ports:
      - "14483:1443"
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:alpine
# version: "3"
# services:
#   web:
#     image: send:latest
#     links:
#       - redis
#     ports:
#          - "1443:1443"
#     environment:
#       - REDIS_HOST=redis
#       - NODE_ENV=production
#   redis:
#     image: redis:alpine
